/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        outfit: ["Outfit", "sans-serif"],
      },
      colors: {
        primary: "#465fff",
        stroke: "#e2e8f0",
        strokedark: "#2e3a47",
        boxdark: "#1c2434",
        "boxdark-2": "#242e42",
        "form-input": "#1c2434",
        "form-strokedark": "#2e3a47",
        "meta-1": "#dc3545",
        "meta-2": "#ffc107",
        "meta-3": "#10b981",
        "meta-4": "#3b82f6",
        gray: {
          2: "#f8f9fa",
          50: "#f9fafb",
          100: "#f2f4f7",
          200: "#e4e7ec",
          300: "#d0d5dd",
          400: "#98a2b3",
          500: "#667085",
          700: "#344054",
        },
        brand: {
          50: "#ecf3ff",
          100: "#dde9ff",
          500: "#465fff",
          600: "#3641f5",
        },
      },
      boxShadow: {
        default: "0 4px 12px rgba(0, 0, 0, 0.04)",
        card: "0 2px 8px rgba(0, 0, 0, 0.06)",
        "theme-md": "0px 4px 8px -2px rgba(16, 24, 40, 0.1), 0px 2px 4px -2px rgba(16, 24, 40, 0.06)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
  safelist: [
    // Lista explícita de clases críticas de TailAdmin (sin patrones que generen warnings)
    'bg-boxdark',
    'bg-boxdark-2',
    'dark:bg-boxdark',
    'dark:bg-boxdark-2',
    'border-stroke',
    'border-strokedark',
    'dark:border-strokedark',
    'border-form-strokedark',
    'dark:border-form-strokedark',
    'text-meta-1',
    'text-meta-2',
    'text-meta-3',
    'text-meta-4',
    'bg-meta-1',
    'bg-meta-2',
    'bg-meta-3',
    'bg-meta-4',
    'bg-meta-4/10',
    'bg-gray-2',
    'bg-gray-50',
    'bg-gray-100',
    'dark:text-gray-300',
    'dark:bg-form-input',
    'dark:bg-gray-800',
    'dark:text-gray-100',
    'shadow-default',
    'shadow-card',
    'shadow-theme-md',
    'bg-primary',
    'hover:bg-primary',
    'focus:border-primary',
    'dark:focus:border-primary',
  ],
};