/*
  Warnings:

  - The `condicion` column on the `pqrs` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- CreateEnum
CREATE TYPE "Condicion" AS ENUM ('APAGADA', 'ENCENDIDA_24H', 'INTERMITENTE', 'POCA_ILUMINACION', 'BAJA_INTENSIDAD', 'PARPADEO', 'FALLA_ELECTRICA', 'FALLA_FOTOCONTROL', 'LUMINARIA_DANADA', 'LUMINARIA_CAIDA', 'POSTE_INCLINADO', 'POSTE_CAIDO', 'VANDALISMO', 'HURTO_LUMINARIA', 'HURTO_CABLEADO', 'OBSTRUCCION_ARBOL', 'ACCIDENTE_TRANSITO', 'LUMINARIA_INEXISTENTE', 'SOLICITUD_NUEVA', 'REUBICACION', 'APOYO_MUNICIPAL', 'MANTENIMIENTO_PREVENTIVO', 'REVISION_TECNICA', 'RECLAMACION_IAP', 'DERECHO_DE_PETICION', 'INFORMACION', 'OTRO', 'REPOTENCIACION', 'MODERNIZACION', 'RECLAMO_IMPUESTO', 'SERVICIO_AP');

-- CreateEnum
CREATE TYPE "SectorPqr" AS ENUM ('CABECERA_MUNICIPAL', 'OCHALI', 'EL_PUEBLITO', 'EL_CEDRO', 'CEDENO', 'LLANOS_DE_CUIVA', 'LA_LOMA');

-- AlterTable
ALTER TABLE "pqrs" ALTER COLUMN "prioridad" SET DEFAULT 'BAJA',
DROP COLUMN "condicion",
ADD COLUMN     "condicion" "Condicion";
